### ISSUE TITLE
"note show keyword" is case sensitive, need an option to search case insensitive...

### ISSUE THREAD

**Issue by ArgosOz** [gumieri/note#12]
Since it's impossible to remember which words have capitalized letters, it's important to be able to search case insensitively.

**Comment by gumieri** [comment]
That's true.
I am going to make case insensitive by default and use the flag option `--case-sensitive` / `-s` (like ripgrep) if someone want to use case sensitive.

**Comment by gumieri** [comment]
PR #13 

Release https://github.com/gumieri/note/releases/tag/v1.2.0
