### ISSUE TITLE
request: binary for armv6h (gcc refers to it as armv6l)

### ISSUE THREAD

**Issue by Spacewalker2** [gumieri/note#14]
Hello,

thanks for this useful program. It would be cool when I could use it on my raspberry pi. I do not have any experience with go so I ask here maybe you can compile a armv6h version for me.

Thanks!

**Comment by gumieri** [comment]
Hello,

Sorry for the late reply!
As far as I know it is realy easy to compile to `arm` but I know nothing about raspberry pi. The OS is linux right?
I gonna add the build for `GOOS=linux GOARCH=arm` and `GOOS=linux GOARCH=arm64`. After that I would like to know if it worked for you.

For reference the supported archtectures by go can be found [here](https://golang.org/doc/install/source#environment).

Edit: I found [this documentation](https://github.com/golang/go/wiki/GoArm) about Go ARM.

**Comment by gumieri** [comment]
Hi @Spacewalker2.
Here is the build: https://github.com/gumieri/note/releases/tag/v1.2.1

Please let me know if it worked for you.
The Issue will be closed but if you find any trouble you are free to re-open it.

**Comment by Spacewalker2** [comment]
Hello @gumieri,

it worked as expected. Thanks! I tried gccgo by myself but I got a lot of error messages. Thanks for the urls I will study them.
