### ISSUE TITLE
note naming is wonky

### ISSUE THREAD

**Issue by blutgens** [gumieri/note#15]
If you have 10 notes and you create a new one, the new note also gets created as number 10.
If you then delete a note, then try to create a new note, it will also get created with the number 10 in the id field, it won't re-use the deleted number. 

One can create the file with touch however, and fix it. One can also manually rename the new number 10 file with a higher number and 'note' will happily make use of it with it's new id.

**Comment by gumieri** [comment]
Sorry for the late reply. I'm going to check it asap.
